name: Uploading zip to S3 ${{ github.event.inputs.file }}
on:
   workflow_dispatch:
     inputs:
       release_tag:
         description: Enter tag name
         required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: convert to zip
        run: |
          zip -qq -r test.zip ${{github.workspace}}/TestAction/
      - name: Deploy files to S3 bucket 
        run: |
          aws s3 sync ${{github.workspace}}/ s3://testbuckettodeletedata/test2/Action/ --exclude "*" --include "*.zip"
          echo release_tag
